fieldLayouts:
  4df3dde1-0af3-4aa8-9e13-154a9b3a7792:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b0ba8614-e926-4208-a71a-84edb8e69966
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d581d900-549f-43a8-8f3f-63010ac19c34
        userCondition: null
fs: site
handle: site
name: Site
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
